### ISSUE TITLE
Small feedback on the readme

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-jni#21]
I'm building `bdk-jni` right now and I just wanted to share some small feedback I have regarding the readme. Note that I am building on an Ubuntu 20.04 distro.

1. The first codeblock is meant for MacOS users. Its first line could be a comment mentioning it:
```sh
# macOS
sudo mv openjdk-15_osx-x64_bin.tar.gz /Library/Java/JavaVirtualMachines/
cd /Library/Java/JavaVirtualMachines/
sudo tar -xzf openjdk-15_osx-x64_bin.tar.gz
sudo rm openjdk-15_osx-x64_bin.tar.gz
```
<br/>

2. My first try at building the library failed, with gradle returning the following error message:
```sh
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable 
or by setting the sdk.dir path in your project's local properties file at '/home/username/repos/bdk-jni/local.properties'.
```

I did build the library a few weeks back and didn't get this problem (is the reliance on this environment variable new?). The readme could mention that the user needs to have that local variable defined, and an example as to where it usually is (just like you have it for the `ndk`, which is great).
<br/>

3. It was unclear to me which library I should use for testing in my app. Both the release and the debug versions are built and available my local maven repository. Maybe one line about this just to explain which one to use for what situation?
<br/>

4. The instructions recommend adding mavenLocal() to the repositories section of my `build.gradle` file, but I found 2 such sections in my file (under `buildscript` and `allprojects`). After looking at the BDWallet equivalent file, I knew I needed to put it in both places, but that could be added to the text to remove that little bit of confusion.
<br/>

Otherwise working great! Will continue to gather feedback as I work my way through it. 

I'm happy to open the PR to fix those little nits if you'd like.

Cheers!

**Comment by notmandatory** [comment]
Thanks for the feedback, yes please go ahead and open a PR to update the README.

**Comment by thunderbiscuit** [comment]
A few questions for you @notmandatory. 

I cannot find the `ANDROID_SDK_ROOT` environment variable mentioned anywhere in the codebase. Was this a problem only on my end of things and has nothing to do with `bdk-jni`? I did have to update my OpenJDK which was not as easy as I thought I'd be so I might have messed something up there. If it is just a problem on my end, I don't think I should mention/add it in the readme. Otherwise I'll add a line mentioning that users should make sure they have that environment variable set when building.

What should I say about the `bdk-jni-debug` version of the library? When is it better to use the debug version than the main one? I'm still learning this myself so not sure of the tradeoff space.

From what I can read on StackOverflow, I now think that the `mavenLocal()` repository does not need to be included in the `buildscript` part of the `build.gradle` file for the purpose of `bdk-jni` (only in the `allprojects` section). Do you think that's correct? If so I'll mention that section as the place to add the local repository.

**Comment by notmandatory** [comment]
1. I agree you should add `# macOS` and since you have Ubuntu also add those steps in the same spot if you want
2. I don't have `ANDROID_SDK_ROOT` in my env on my ubuntu system and `./gradlew build` works fine for me
3. for now everyone needs to use the locally built `bdk-jni-debug` version so it can be debugged and used locally in the IDE. Eventually we'll publish a public [release build](https://developer.android.com/studio/publish/preparing#publishing-build) signed with an official BDK signing key
4.  Yes I agree for app developers using `bdk-jni` the `Repositories { mavenLocal() ...` goes into `allprojects { ` in the top level `build.gradle` file. This is also just for users who are building and locally publishing their own local `bdk-jni-debug` so applies to anyone reading the `bdk-jni` README. Once we get `BDWallet` cleaned up some more we can point them there as an example to follow.

**Comment by thunderbiscuit** [comment]
PR #22 with fixes for the above discussion was merged. Closing this issue.
