### ISSUE TITLE
BDK-JNi gives error when we change the descriptor but not the name of wallet

### ISSUE THREAD

**Issue by mbcse** [bitcoindevkit/bdk-jni#48]
When I initialise a wallet like this 
 ` walletPtr = Lib().constructor(
            WalletConstructor(
                name = name,
                network = Network.testnet,
                path = getDataDir(),
                descriptor = descriptor,
                change_descriptor = change_descriptor,
                electrum_url = electrumURL,
                electrum_proxy = null,
            )
  ) `
And later on change the descriptor but not the name, it throws error something like you can't create wallet as it is already taken. 
If I change the name the error disappears. Can anyone explain what is happening and if those name's are getting reserved then how to delete/free them?

cc @thunderbiscuit

**Comment by thunderbiscuit** [comment]
I think this is happening because the database is part of and handled by the native lib file. If you have different projects and they all use the same native library `libbdk_jni.so` file, they will have access to each others' wallets, and wallets with the same name will conflict.

The android version does not have this problem because the library ships with the native file in it. I think the better way to deal with this in the short term is to create/duplicate a native library for each application you use.

**Comment by notmandatory** [comment]
This is the same error  you would get in the `bdk-cli` when you use the same wallet name for two different descriptors. The `bdk` database stores a cache of blockchain data that is specific to each descriptor and the library adds and check the "checksum" of the descriptor in the wallet db to make sure they always match. If they don't match it throws an error. 
The error you're probably getting is:
https://docs.rs/bdk/0.10.0/bdk/enum.Error.html#variant.ChecksumMismatch

**Comment by thunderbiscuit** [comment]
Closing this now as this library is deprecated.
